rule runall:
    input:
        "../results/regression-output.md",
        "../results/heatmap.png",
        "../results/lineplot.png",
        "../results/lmplot.png",
        "../results/pairplot.png"

rule acquisition:
    input:
        "checksums/checksums.txt"
    output:
        "../data/raw/ncei.csv",
        "../data/raw/iowa1.csv",
        "../data/raw/iowa2.csv",
        "../data/raw/iowa3.csv"
    shell:
        "python acquisition.py"

rule integration:
    input:
        "../data/raw/ncei.csv",
        "../data/raw/iowa1.csv",
        "../data/raw/iowa2.csv",
        "../data/raw/iowa3.csv"
    output:
        "../data/processed/integrated.csv"
    shell:
        "python integration.py"

rule analysis:
    input:
        "../data/processed/integrated.csv"
    output:
        "../results/heatmap.png",
        "../results/lineplot.png",
        "../results/lmplot.png",
        "../results/pairplot.png"
    shell:
        "python analysis.py"

rule modeling:
    input:
        "../data/processed/integrated.csv"
    output:
        "../results/regression-output.md"
    shell:
        "python modeling.py"
